---
images_folder: "./datasets/words/"
labels_file: "./datasets/labels.json"
image:
    image_size:
        y_size: 128
        x_size: 384
        num_channels: 1
    convert_to_grayscale: false
train:    
    train_on_subset: 
        enabled: false
        random_seed: 33
        dataset_fraction: 0.8   
    optimizer: "adam"      #adam, adagrad, adadelta, rmsprop, sgd
    learning_rate: 0.001  
    batch_size: 256   
    num_epochs: 50
    use_multiprocessing: false
    num_workers: 1
    weights_initialization: 
        use_pretrained_weights: true
        restore_from: "./experiments/snapshot_last.h5"
    output:
        output_graph: "./snapshots/graph.json"
        output_weights: "./snapshots/weights.h5"
predict: 
    graph_file: "./snapshots/graph.json"
    weights_file: "./snapshots/weights.h5"
    batch_size: 256
network:
    num_filters: [16, 32, 64, 128, 256, 512]
    conv_kernels: [[7, 7], [5, 5], [5, 5], [3, 3], [3, 3], [3, 3]]
    use_batch_norm: true
    latent_dim: 512
    max_seq_lenght: 55
    loss: "categorical_crossentropy"
data_aug: 
    use_data_aug: false
    rotation_range: 5 
    width_shift_range: 0.05
    height_shift_range: 0.05
    zoom_range: [0.95, 1.05]
    horizontal_flip: false
    vertical_flip: false
    shear_range: 2.
callbacks:
    early_stopping: 
        enabled: true
        monitor: "val_loss"
        patience: 10
    model_best_checkpoint: 
        enabled: true
        out_file: "./experiments/snapshot_best.h5"
        monitor: "val_loss"
    model_last_checkpoint: 
        enabled: true
        out_file: "./experiments/snapshot_last.h5"
    tensorboard: 
        enabled: false
        log_dir: "./tensorboard/"
    reduce_lr_on_plateau: 
        enabled: false
        monitor: "val_loss"
        factor: 0.1
        patience: 10
